### ISSUE TITLE
questions about locking

### ISSUE THREAD

**Issue by hoffoo** [armon/consul-api#14]
Is it possible to get the session id that has locked a key?

Also what is involved in locking? Consul doesn't seem to prevent me from deleting a locked key, is it only to be used with Acquire and Release, or should it also stop me from making changes?

**Comment by armon** [comment]
@hoffoo Yes, you can read the key with a Get and then inspect the `Session` field which will contain the SessionID. Consul locks are advisory and they do not enforce holding the lock to modify the key.

Hope that helps!

**Comment by hoffoo** [comment]
Makes sense, thank you!
