### ISSUE TITLE
http_proxy env variables handled improperly

### ISSUE THREAD

**Issue by vbichov** [armon/consul-api#15]
link to original issue:
https://github.com/hashicorp/consul-template/issues/132#issuecomment-67775902

When a proxy is defined, the client parses it in a naive and very wrong way:
when a Dockerfile has:
ENV http_proxy "http://web-proxy:8080"
you get:
http: error connecting to proxy http://"http://web-proxy:8080%22: dial tcp: unknown port tcp/

it can't discern " , or http, and it transformed the last " to Unicode.

**Comment by armon** [comment]
We've migrated the API client, so I've recreated the ticket on the Consul issue tracker.
Closing here.
