### ISSUE TITLE
KV().List() not updating on deletes with a group of keys?

### ISSUE THREAD

**Issue by cleung2010** [armon/consul-api#5]
The func (*KV)List is not returning me a list if I have two or more keys and delete one unless it's the last one that is being deleted. Is this intended or am I missing something?

More specifically, it's not getting triggered here https://github.com/ryanbreen/fsconsul/blob/master/watch.go#L172 unless the list is empty or I am adding keys.

**Comment by armon** [comment]
Should be fixed upstream. This will appear in Consul 0.5
